FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps/web ./apps/web
COPY packages ./packages

RUN npm install -g pnpm
RUN pnpm install 

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

RUN pnpm run db:generate
RUN pnpm run db:build
RUN pnpm run backend:build

EXPOSE 3000
CMD ["sh", "-c", "pnpm run db:migrate && pnpm run web:start"]

