name: Deploy the backend to dev server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./docker/dockerfile.backend
          push: true
          tags: vinod057/monorepo-backend:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/monorepo-backend:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/monorepo-backend:cache,mode=max

      - name: Deploy via SSH to VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            if command -v docker &> /dev/null
            then
                echo "✅ Docker is already installed."
                docker --version
            else
                echo "Installing Docker..."
                sudo apt-get update
                sudo apt-get install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
            fi
          
            # Always run Docker commands with sudo in CI/CD
            sudo docker system prune --all --force
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/monorepo-backend:${{ github.sha}}
            sudo docker stop backend-container || true
            sudo docker rm backend-container || true
            sudo docker run -d --name backend-container -p 4000:4000 ${{ secrets.DOCKERHUB_USERNAME }}/monorepo-backend:${{ github.sha}}
            sudo docker port backend-container
            sudo docker exec backend-container curl -s http://localhost:4000/
            sudo docker logs backend-container


